# Generated by Django 6.0.7 on 2026-07-20 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Singer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='singer name', max_length=225)),
                ('description', models.TextField(blank=True, help_text='About singer', null=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Ablum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='singer Ablum title', max_length=255)),
                ('release_date', models.DateField(help_text='singer Ablum Release Date')),
                ('singer', models.ForeignKey(help_text='singer that owns the Album', on_delete=django.db.models.deletion.CASCADE, to='core.singer')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
