# Generated by Django 6.0.7 on 2026-07-21 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ablum',
            new_name='Album',
        ),
    ]
